# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.10'
      - name: tests
        run: |
          python --version
          which python
          pip --version
          pip install --upgrade pip
          command -v pipenv &> /dev/null || pipx install pipenv
          command -v docker &> /dev/null || brew install docker
          pip install docker-compose
          docker compose --help
          brew install mariadb-connector-c
          PIPENV_VENV_IN_PROJECT=1 make tests
